standard: nograph.cpp
	g++ -o standard nograph.cpp -lSDL2 -std=c++14
optimised: nograph.cpp
	g++ -o optimised nograph.cpp -lSDL2 -std=c++14 -O3
profiled: nograph.cpp
	g++ -o profiled nograph.cpp -lSDL2 -std=c++14 -pg
