standard: timepix.cpp
	g++ -o standard timepix.cpp -lSDL2 -std=c++14
optimised: timepix.cpp
	g++ -o optimised timepix.cpp -lSDL2 -std=c++14 -O3
profiled: timepix.cpp
	g++ -o profiled timepix.cpp -lSDL2 -std=c++14 -pg
