standard: radii.cpp
	g++ -o standard radii.cpp -lSDL2 -lpthread -std=c++14
optimised: radii.cpp
	g++ -o optimised radii.cpp -lSDL2 -lpthread -std=c++14 -O3
profiled: radii.cpp
	g++ -o profiled radii.cpp -lSDL2 -lpthread -std=c++14 -pg
