standard: interface.cpp
	g++ -o standard interface.cpp -lSDL2 -std=c++14
optimised: interface.cpp
	g++ -o optimised interface.cpp -lSDL2 -std=c++14 -O3
profiled: interface.cpp
	g++ -o profiled interface.cpp -lSDL2 -std=c++14 -pg
