standard: xandu.cpp
	g++ -o standard xandu.cpp -lSDL2 -lpthread -std=c++14
optimised: xandu.cpp
	g++ -o optimised xandu.cpp -lSDL2 -lpthread -std=c++14 -O3
profiled: xandu.cpp
	g++ -o profiled xandu.cpp -lSDL2 -lpthread -std=c++14 -pg
