standard: kandkv.cpp
	g++ -o standard kandkv.cpp -lSDL2 -lpthread -std=c++14
optimised: kandkv.cpp
	g++ -o optimised kandkv.cpp -lSDL2 -lpthread -std=c++14 -O3
profiled: kandkv.cpp
	g++ -o profiled kandkv.cpp -lSDL2 -lpthread -std=c++14 -pg
